driver: pyez
demo_ref_doc_url: static/docs/readthedocs-html-version/index.html
jtac_url: https://support.juniper.net/support/
ws_client_protocol: ws
ws_client_ip: 127.0.0.1
ws_client_port: 8670
git_protocol: http
git_host: 10.11.111.180
git_http_port: 9080
git_ssh_port: 3022
git_login_url: /oauth/token
git_repo_url: root/cso_ops
git_device_conf_dir: config
git_user: root
git_password: juniper123
git_branch: master
tmp_dir: /tmp/cso-ui/data
log_dir: /tmp/cso-ui/log
usecases_dir: usecases
baselog: cso-ui.log

IS_SSL: False
DEMONIZE: False
UI_ADDRESS: 127.0.0.1
UI_PORT: 8670