useCase0:
  title: Use Case 0 - Base
  playbook: pb.yml
  directory: useCase0/
  description: Demonstrate Application detection for SD-WAN and Static SD-WAN policy and Dynamic SD-WAN policy
  image: dummy.png
  delete: false

useCase1:
  title: Use Case 1 - Local Break Out at Spoke
  playbook: pb.yml
  directory: useCase1/
  description: Demonstrate ability of the site to breakout internet traffic form the site itself
  image: dummy.png
  delete: false

useCase2:
  title: Use Case 2 - MultiHoming
  playbook: pb.yml
  directory: useCase2/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase3:
  title: Use Case 3 - Spoke Redundancy / Dual Spoke
  playbook: pb.yml
  directory: useCase3/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase4:
  title: Use Case 4 - Device RMA
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase5:
  title: Use Case 5 - Realtime optimized
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase6:
  title: Use Case 6 - Full Mesh
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase7:
  title: Use Case 7 - VNF Integration
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase8:
  title: Use Case 7 - Multicloud
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false