deployed_usecase: useCase2
usecases:
  useCase0:
    title: Use Case 0 - Base
    playbook: pb.yml
    directory: useCase0
    description: Demonstrate Application detection for SD-WAN and Static SD-WAN policy
      and Dynamic SD-WAN policy
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase1:
    title: Use Case 1 - Local Break Out at Spoke
    playbook: pb.yml
    directory: useCase1
    description: Demonstrate ability of the site to breakout internet traffic form
      the site itself
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase2:
    title: Use Case 2 - MultiHoming
    playbook: pb.yml
    directory: useCase2
    description: MultiHoming
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: true

  useCase3:
    title: Use Case 3 - Spoke Redundancy
    playbook: pb.yml
    directory: useCase3
    description: Demonstrate spoke redundancy
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase4:
    title: Use Case 4 - Device RMA
    playbook: pb.yml
    directory: useCase4
    description: Demonstrate return merchandise authorization
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase5:
    title: Use Case 5 - Realtime optimized
    playbook: pb.yml
    directory: useCase5
    description: Demonstrate realtime traffic optimization
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase6:
    title: Use Case 6 - Full Mesh
    playbook: pb.yml
    directory: useCase6
    description: Demonstrate Full Mesh
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase7:
    title: Use Case 7 - VNF Integration
    playbook: pb.yml
    directory: useCase7
    description: Demonstrate simple VNF integration
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false

  useCase8:
    title: Use Case 8 - Multicloud
    playbook: pb.yml
    directory: useCase8
    description: MultiCloud with AWS
    image: dummy.png
    image_deployed: dummy_deployed.png
    delete: false
    deployed: false
