deployed_usecase: useCase9
usecases:
  useCase0:
    title: Reset QFX to SD-WAN BASIC
    playbook: pb.yml
    directory: useCase0
    description: Load or reset config of QFX5100 with SD-WAN underlay configuration
      but do not touch any other Device
    image: UC0.PNG
    image_deployed: UC0.PNG
    delete: false
    deployed: true

  useCase1:
    title: Reset Hub1 to lab-default
    playbook: pb.yml
    directory: useCase1
    description: Load or reset config of Hub1 (SRX1500-1) so that you can load Stage-1
      config to it but do not touch any other Device
    image: UC1.PNG
    image_deployed: UC1.PNG
    delete: false
    deployed: true

  useCase2:
    title: Reset SRX-Spoke to lab-default
    playbook: pb.yml
    directory: useCase2
    description: Load or reset config of SRX-Spoke (SRX345-1) so that you can start
      ZTP Provision but do not touch any other Device
    image: UC2.PNG
    image_deployed: UC2.PNG
    delete: false
    deployed: true

  useCase3:
    title: Zeroize NFX250-1 to lab-default
    playbook: pb.yml
    directory: useCase3
    description: Zeroize NFX250-1 so that you can start ZTP Provision but do not touch
      any other Device
    image: UC3.PNG
    image_deployed: UC3.PNG
    delete: false
    deployed: false

  useCase4:
    title: Zeroize NFX250-2 to lab-default
    playbook: pb.yml
    directory: useCase4
    description: Zeroize NFX250-2 so that you can start ZTP Provision but do not touch
      any other Device
    image: UC4.PNG
    image_deployed: UC4.PNG
    delete: false
    deployed: true

  useCase5:
    title: Multi-Hub (or Hub-Redundancy)
    playbook: pb.yml
    directory: useCase5
    description: This will ADD the second Hub config to the QFX5100 and Zeroise Hub2
      so that you can load Stage-1. Hub1 and any Spokes are not touched. It is assumed
      that the SD-WAN basic scenario is already loaded.
    image: UC5.PNG
    image_deployed: UC5.PNG
    delete: false
    deployed: true

  useCase6:
    title: Dual Spoke (HA via NFX250)
    playbook: pb.yml
    directory: useCase6
    description: This will deactivate the SD-WAN BASIC config on the QFX5100 and load
      a complete new config for this lab. Hub1 will be resetted so that you can load
      Stage-1. The two NFX250 that you need for this lab are also Zeroized and brought
      into a state that you can start ZTP Provision.
    image: UC6.PNG
    image_deployed: UC6.PNG
    delete: false
    deployed: false

  useCase7:
    title: Partial Mesh & Site-GW
    playbook: pb.yml
    directory: useCase7
    description: This will ADD a Site-GW config for the second Hub config to the QFX5100.
      It will Zeroise Hub2 so that you can load Stage-1. Hub1 and any Spokes are not
      touched. It is assumed that the SD-WAN basic scenario is already loaded.
    image: UC7.PNG
    image_deployed: UC7.PNG
    delete: false
    deployed: false

  useCase8:
    title: Device RMA (via two NFX250)
    playbook: pb.yml
    directory: useCase8
    description: This will deactivate the SD-WAN BASIC config on the QFX5100 and load
      a complete new config for this lab. The second NFX250 will be Zeroized so that
      you can start ZTP as a RMA Device. Hub1 and the NFX250-1 are not touched as
      they may be already be provisioned from other labs.
    image: UC8.PNG
    image_deployed: UC8.PNG
    delete: false
    deployed: false

  useCase9:
    title: Lab init to SD-WAN BASIC and prepare Devices
    playbook: pb.yml
    directory: useCase9
    description: This resets the entire LAB (without Hub2). Hub1 and the 3 Spokes
      are Zeroized and prepared for the Lab. Any EXISTING config of QFX5100 is overwritten
      with SD-WAN BASIC configuration and the default lab config.
    image: UC9.PNG
    image_deployed: UC9.PNG
    delete: false
    deployed: true
