useCase0:
  title: Use Case 0 - Base
  playbook: pb.yml
  directory: useCase0/
  description: Base Configuration
  image: dummy.png
  delete: false

useCase1:
  title: Use Case 1 - Local Break Out at Spoke
  playbook: pb.yml
  directory: useCase1/
  description: Local Break Out at Spoke
  image: dummy.png
  delete: false

useCase2:
  title: Use Case 2 - MultiHoming
  playbook: pb.yml
  directory: useCase2/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase3:
  title: Use Case 3 - MultiHoming
  playbook: pb.yml
  directory: useCase3/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase4:
  title: Use Case 4 - MultiHoming
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase5:
  title: Use Case 5 - MultiHoming
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase6:
  title: Use Case 6 - MultiHoming
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false

useCase7:
  title: Use Case 7 - MultiHoming
  playbook: pb.yml
  directory: useCase4/
  description: MultiHoming
  image: dummy.png
  delete: false