---
name: "UseCase2"
targets:
  vsrx01:
    address: 10.11.111.251
    port: 32771
    user: root
    password: juniper123
    mode: telnet
    template: vsrx01.j2
tasks:
  Zerorize: True
  Configure: True
  Copy: True