---
name: "UseCase2"
targets:
  vsrx01:
    mode: telnet
    address: 10.11.111.251
    port: 32771
    user: root
    password: juniper123
    template: vsrx01.j2
    template_data: vsrx01.yml
    copy_src: phcd-ca.crt
    copy_dst: /tmp/phcd-ca.crt

tasks:
  Render:
    enabled: True
  Zerorize:
    enabled: True
  Configure:
    enabled: True
    merge: False
    override: False
    update: True
    confirm: False
  Copy:
    enabled: True