---
name: "UseCase2"
targets:
  vsrx01:
    mode: telnet
    address: 10.11.111.251
    port: 32771
    user: root
    password: juniper123
    tasks:
      Render:
        enabled: True
        template: vsrx01.j2
        template_data: vsrx01.yml
      Zerorize:
        enabled: True
      Configure:
        enabled: True
        merge: False
        override: False
        update: True
        confirm: False
        sync: False
        template: vsrx01.j2
        template_data: vsrx01.yml
      Copy:
        enabled: True
        src: phcd-ca.crt
        dst: /tmp/phcd-ca.crt
  vsrx02:
    mode: telnet
    address: 10.11.111.251
    port: 32772
    user: root
    password: juniper123
    tasks:
      Render:
        enabled: True
      Zerorize:
        enabled: True
      Configure:
        enabled: True
        merge: False
        override: False
        update: True
        confirm: False
        sync: False
        template: vsrx01.j2
        template_data: vsrx01.yml
      Copy:
        enabled: True
        src: phcd-ca.crt
        dst: /tmp/phcd-ca.crt